.github/workflows/publish.yaml

feat: Dockerize and publish deployment agent image

---

charts/deployment-operator/Chart.yaml

Fixes the chart versioning and should initiate publishing of the chart.

fix: proper chart versioning

---

pkg/sync/loop.go

Apply syncs to the recursive resource list and enable background pruning

Improve resource pruning

---

.github/workflows/ci.yaml
.github/workflows/semantic-pr.yaml
.releaserc

This PR sets up semantic release so on each push to master a new release is created following proper semver conventions.

ci: setup semantic release

---

.github/workflows/publish.yaml
pkg/sync/loop.go
pkg/sync/predicates.go
pkg/sync/status.go

feat: Resolve lint issues

---

charts/deployment-operator/Chart.yaml

includes runtime service fetching

feat: Release v0.3.27

---

pkg/sync/status.go

the `if ds.Successful == toDelete` condition is true when resources are terminating. For a long deletion process, the resources are still alive even if the service doesn't exist.

fix: delete logic

---

go.mod
go.sum
pkg/manifests/template/helm.go

Support fetching values from the given values file list and merging them into the full values given to helm template

feat: Add helm values files list support

---

charts/deployment-operator/Chart.yaml

includes deletion fixes, and multi-values file support

Release v0.3.28

---

go.mod
go.sum
pkg/websocket/socket.go

Needed to fix some issues in the gophoenix fork around socket heartbeating, this seems to be more correct.  Will test for a while to confirm

feat: Use better socket keepalive logic

---

pkg/sync/loop.go

change to default DeletePropagationBackground

feat: change DeletePropagationPolicy

---

charts/deployment-operator/Chart.yaml

includes some minor fixes to agent error handling

Bump to 0.3.29

---

charts/deployment-operator/Chart.yaml
pkg/websocket/socket.go

Bumps agent to 0.3.30 to release some new updates

feat: Release v0.3.30

---

charts/deployment-operator/Chart.yaml

handles a minor nil pointer edge case

feat: release v0.4.2

---

go.mod
go.sum
pkg/agent/agent.go
pkg/client/cluster.go
pkg/ping/build.go
pkg/ping/distro.go
pkg/ping/pinger.go

Adds the ability to detect cluster distribution and return that info in ping requests.  Also refactor pinging into its own package as the logic might become more expansive as this evolves.

Extended Ping

---

.github/workflows/publish.yaml
charts/deployment-operator/Chart.yaml

feat: release v0.4.3

---

pkg/manifests/template/helm.go
pkg/sync/scraper.go

If there are multiple versions of the same add-on we want people to know about the lowest semver.

Ensure lowest version wins for runtime service shipper

---

.github/workflows/publish.yaml

Was referencing wrong job name

fix: Fix github action

---

charts/deployment-operator/Chart.yaml
charts/deployment-operator/templates/deployment.yaml
charts/deployment-operator/values.yaml
go.mod
go.sum
pkg/manifests/template/helm.go

Will help with usecases where pod labels need to be set explicitly

Minimal deployment operator change

---

internal/utils/kubernetes.go
pkg/client/pipelines.go
pkg/manifests/template/raw.go

Will be use to round out the full service context api setup

feat: Begin working on sideloading contexts

---

pkg/controller/pipelinegates/reconciler.go
pkg/controller/service/reconciler.go
pkg/controller/service/reconciler_status.go

Some debug messages are being emitted that don't necessarily need to be in the production build of the agent.

feat: Reduce some unnecessary logging

---

internal/errors/base.go
pkg/controller/service/reconciler.go

Move deletion before fetching manifest to avoid templating error

feat: tune service deletion

---

internal/controller/pipelinegate_controller.go

Use gate.Status.GateUpdateAttributes() to determine console update

feat: improve check status

---

pkg/client/pipelines.go

feat: don't set job's ttl

---

pkg/controller/controller_manager.go
pkg/manifests/template/helm_test.go
pkg/manifests/template/raw_test.go

fix: controller manager polling

---

charts/deployment-operator/templates/deployment.yaml
charts/deployment-operator/values.yaml

Is particularly useful for configuring custom CAs and other config data

feat: Add hooks to specify additional volumes and additional volume mounts

---

go.mod
go.sum
pkg/manifests/template/raw.go

This can help parameterize services by cluster in global services

fix: Add cluster metadata fetch

---

pkg/manifests/template/helm.go
pkg/manifests/template/tpl.go

For users who are more accustomed to go templates from helm itself.

feat: Support .tpl extensions for values files

---

go.mod
go.sum
pkg/manifests/template/helm.go

The api now has this as an available attribute, we need to let the agent respect it as well.

feat: Support plumbing helm release name into agent

---

pkg/manifests/template/raw.go
pkg/manifests/template/utils.go

Looks like the monkeypatching has some weird golang bug so just directly implement these

fix: Custom implement ternary + default

---

internal/controller/constraint_controller.go

We need to grab the description/recommendation from the bundle data json blob

feat: Better policy constraint data fetch

---

go.mod
go.sum
internal/controller/constraint_controller.go

Needed to flesh out last part of policy view

feat: Add constraint enforcement

---

internal/controller/constraint_controller.go

Need to sanitize it a bit before then.

fix: For incomprehensible reasons, google stringifies this data field

---

cmd/agent.go
go.mod
go.sum
pkg/controller/service/reconciler.go
pkg/manifests/template/helm.go

Fetch API versions every 5min. Use those versions for helm templating

feat: add helm capabilities API versions

---

.github/workflows/publish-harness.yaml
cmd/harness/main.go
pkg/controller/stacks/reconciler.go
pkg/harness/controller/controller.go
pkg/harness/controller/controller_hooks.go
pkg/harness/controller/controller_options.go
pkg/harness/controller/controller_types.go
pkg/harness/controller/executor.go
pkg/harness/controller/executor_options.go
pkg/harness/controller/executor_types.go
pkg/harness/exec/exec.go
pkg/harness/exec/exec_options.go
pkg/harness/exec/exec_types.go
pkg/harness/stackrun/types.go
pkg/harness/tool/ansible/ansible.go
pkg/harness/tool/terraform/terraform.go
pkg/harness/tool/v1/types.go

feat(harness): support approval flow and more

---

go.mod
go.sum
pkg/controller/stacks/job.go
pkg/controller/stacks/reconciler_test.go

The stack run controller sets the stack ref once it creates the run job

feat: set jobRef on stack run

---

pkg/harness/tool/terraform/terraform.go
pkg/harness/tool/terraform/terraform_types.go

tf binary should handle reading the state from the backend or local file

fix: use terraform show to get state instead of reading local file

---

.github/workflows/publish-harness.yaml
cmd/harness/main.go
go.mod
go.sum
pkg/harness/controller/controller.go
pkg/harness/controller/controller_hooks.go
pkg/harness/controller/controller_options.go
pkg/harness/controller/controller_types.go
pkg/harness/stackrun/v1/types.go
pkg/harness/tool/ansible/ansible.go
pkg/harness/tool/terraform/api/v4/state.go
pkg/harness/tool/terraform/templates/_override.tf.gotmpl
pkg/harness/tool/terraform/terraform.go
pkg/harness/tool/terraform/terraform_templates.go
pkg/harness/tool/terraform/terraform_types.go
pkg/harness/tool/v1/types.go

feat(harness): add support for tf plural managed state

---

.github/workflows/e2e.yaml
cmd/agent/agent.go
cmd/agent/args/args.go
internal/controller/argorollout_controller.go
internal/controller/pipelinegate_controller.go
internal/controller/requeue.go
internal/controller/restore_controller.go
internal/controller/stackrunjob_controller.go
pkg/applier/filters/cache_filter_test.go
pkg/applier/filters/suite_test.go
pkg/controller/controller_manager.go

- add poller's jitter
- add e2e test for cache filter

add jitter

---

pkg/common/status.go

Don't wait for Synchronized condition until it's fully "ready"

fix: set synced status

---

go.mod
go.sum

Reverts pluralsh/deployment-operator#255

Revert "chore(deps): bump github.com/docker/docker from 24.0.7+incompatible to 25.0.6+incompatible"

---

pkg/common/health_test.go
pkg/controller/namespaces/reconciler_test.go
pkg/controller/namespaces/suite_test.go
pkg/controller/restore/reconciler_test.go
pkg/controller/restore/suite_test.go

- restore controller
- namespace controller

test: add controler's unit tests

---

go.mod
go.sum
internal/controller/kubecostextractor_controller.go

Simply add a few struct fields

feat: Add cpu util/memory util to recommendations extractor

---

go.mod
go.sum
pkg/client/console.go
pkg/client/service.go
pkg/controller/service/reconciler.go
pkg/controller/service/reconciler_status.go
pkg/controller/service/reconciler_test.go
pkg/controller/service/socket_publisher.go
pkg/controller/service/status_collector.go
pkg/manifests/cache.go
pkg/manifests/template/helm.go
pkg/manifests/template/helm_test.go
pkg/manifests/template/kustomize.go
pkg/manifests/template/kustomize_test.go
pkg/manifests/template/raw.go
pkg/manifests/template/raw_test.go
pkg/manifests/template/template.go
pkg/manifests/template/tpl.go
pkg/manifests/template/tpl_test.go
pkg/manifests/template/utils.go
pkg/manifests/template/utils_test.go
pkg/test/mocks/Client_mock.go

This PR is the first part of the deployment operator optimization.

chore: bump console go client

---

pkg/common/health.go
pkg/common/health_test.go
pkg/controller/namespaces/reconciler.go
pkg/controller/pipelinegates/reconciler.go
pkg/controller/service/reconciler_status.go
pkg/controller/stacks/reconciler.go

- remove more low-signal logs
- change health rules for status condition

chore: remove more low-signal logs and change health rules for status condition 

---

internal/controller/scope.go
internal/controller/upgradeinsights_cloudprovider.go
internal/controller/upgradeinsights_controller.go

Small improvement and cleanup of the upgrade insight controller.

feat: surface upgrade insight errors to conditions

---

go.mod
go.sum
pkg/harness/controller/controller.go
pkg/harness/stackrun/v1/types.go

- Added `dryRun` support to stack run
- When in `dryRun` mode, outputs will not be uploaded upon run completion

feat(harness): add dry run support to harness

---

pkg/websocket/socket.go

fix: concurrent map writes

---

internal/controller/clusterdrain_controller.go

- avoid throttling
- give some time to start redeployment

chore: improve ClusterDrain controller

---

charts/deployment-operator/values.yaml

yaml indentation bug, timeout -> timeoutSeconds

fix: Fix probe schemas

---

cmd/agent/console.go
cmd/agent/main.go
internal/controller/clusterdrain_controller.go
pkg/applier/filters/cache_filter_test.go
pkg/cache/resource_cache.go
pkg/cache/resource_cache_entry.go
pkg/cache/resource_cache_test.go
pkg/common/health_test.go
pkg/common/status.go
pkg/common/suite_test.go
pkg/controller/service/reconciler.go
pkg/controller/service/reconciler_status.go
pkg/controller/service/reconciler_test.go
pkg/controller/service/status_collector.go
pkg/scraper/component_scraper.go

Reverts pluralsh/deployment-operator#397

fix: Revert "fix: resource health status"

---

go.mod
go.sum
pkg/cache/discovery_cache.go
pkg/client/cluster.go
pkg/controller/service/reconciler_scraper.go

feat: Support EBPF service mesh type

---

go.mod
go.sum
internal/kubernetes/watcher/retry_watcher.go
pkg/manifests/tarball.go

- add retry to manifest downloads
- fix rare panic

fix: add retry, and fix panic

---

internal/controller/constraint_controller.go
pkg/client/cluster.go
pkg/client/console.go
pkg/client/constraint.go
pkg/controller/service/reconciler_scraper.go
pkg/test/mocks/Client_mock.go

- fix Istio addon discovery
- improve memory allocation

fix: Istio addon discovery

---

cmd/agent/args/args.go
pkg/controller/controller.go
pkg/manifests/tarball.go

This should help more with large multi-repo setups

fix: Add more jitter to manifest caches

---

pkg/controller/controller.go
pkg/manifests/template/template.go

We aren't handling this error case, which can occasionally fire

fix: Fix a panic due to bad os walk

---

charts/deployment-operator/templates/deployment.yaml
charts/deployment-operator/values.yaml
charts/deployment-operator/values.yaml.liquid

This can help with some weird one-off cluster cases

feat: Allow registry customization

---

pkg/cache/db/cache_test.go
pkg/cache/db/queries.go

- fixed an issue with group column in component cache
- slightly refactored tests
- added unit test to cover group column check

fix(db-cache): fix an issue with storing group in component cache db

---

go.mod
go.sum
pkg/cache/db/cache.go
pkg/cache/db/cache_test.go
pkg/cache/db/queries.go
pkg/ping/build.go

Tested with console `sha-34df3ee` on `plrl-dev-aws`.

feat: Add cluster health score to pings

---

pkg/harness/controller/controller.go
pkg/harness/stackrun/v1/types.go
pkg/harness/tool/terraform/modifier.go
pkg/harness/tool/terraform/modifier_types.go
pkg/harness/tool/terraform/terraform.go
pkg/harness/tool/terraform/terraform_types.go
pkg/harness/tool/v1/types.go

Use plan and apply args modifiers directly instead of env vars that break init

fix: terraform parallelism implementation

---

go.mod
go.sum
pkg/manifests/template/helm.go
pkg/manifests/template/helm_test.go
pkg/manifests/template/raw.go

This is my expectation of how lua would behave, which is basically providing the last values files and lua values winning over helm inline values

fix: lua merge order

---

Dockerfile
charts/deployment-operator/templates/deployment.yaml
pkg/manifests/cache.go
pkg/manifests/tarball.go
pkg/manifests/tarball_test.go

- detect splitbrain
-  make /.kube writable
-  add emptyDir volume for /.kube

chore: detect splitbrain

---

go.mod
go.sum
internal/controller/crd_controller.go
pkg/applier/filters/cache_filter.go
pkg/cache/resource_cache.go
pkg/cache/resource_key.go
pkg/manifests/cache.go
pkg/manifests/template/helm.go
pkg/scraper/servergroups.go

* adds mutex
* hook into crd reconciler to find new crds as they come in and start watching
Fixes PROD-3708

fix: Improve resource cache crd detection

---

go.mod
go.sum

fix: Bump polly to v0.3.1

---

cmd/agent/main.go
go.mod
go.sum
pkg/common/k8s.go
pkg/controller/pipelinegates/reconciler.go
pkg/controller/service/reconciler.go
pkg/ping/build.go
pkg/ping/pinger.go

I was able to install a local OpenShift cluster and test it

feat: openshift distro discovery

---

pkg/ping/pinger.go

these are labels not annotations

fix: az inference

---

pkg/manifests/tarball.go

feat: Add a bit more manifest error logging

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/semantic-pr.yaml
charts/deployment-operator/Chart.yaml

Test environment: https://console.plrl-dev-aws.onplural.sh/

chore: Add GitHub confirmation that a deployed agent is available

---

pkg/streamline/store/db_queries.go
pkg/streamline/store/db_store_test.go

Fixes PROD-3992.
Test environment: https://console.plrl-dev-aws.onplural.sh/

fix: Fix DB cache expiration
