pluralsh/deployment-operator

Dockerfile
charts/deployment-operator/Chart.yaml
charts/deployment-operator/templates/deployment.yaml
cmd/main.go
go.mod
go.sum
pkg/manifests/template/raw.go
pkg/sync/constants.go
pkg/sync/loop.go

This will force redeployment of the operator when deploy tokens rotate

feat: Add checksum to operator deployment

---

pkg/agent/agent.go
pkg/client/cache.go
pkg/websocket/socket.go

At the moment the websocket might not matter that much, since it would just get served out of cache, we can confidently expire in that case.

feat: Bust service cache on incoming websocket

---

pkg/manifests/versions.go
pkg/sync/loop.go
pkg/sync/status.go

Kubernetes will occasionally switch kind versions on apply automatically via mutating webhooks, this is fine, but ruins our ability to detect deprecations in manifests, so revert back to manifest versions where we can find them.
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1205855554055664

feat: Avoid version coercion in components

---

.github/configs/cr.yaml
.github/workflows/publish.yaml
charts/deployment-operator/Chart.yaml

This will hopefully make it a bit easier to see and reference chart releases in a self-managed agent experience in CD

feat: Reconfigure chart-releaser to have more direct tag names

---

go.mod
go.sum
pkg/agent/agent.go
pkg/client/cluster.go
pkg/sync/engine.go
pkg/sync/scraper.go

Most of these are detectable by the app.kubernetes.io/{name,part-of,version} labels.  If there are some others that are atypical we can add clauses as needed.

feat: Add basic scrapes for runtime services

---

go.mod
go.sum
pkg/client/service.go
pkg/errors/base.go
pkg/errors/manifests.go
pkg/manifests/tarball.go
pkg/sync/loop.go
pkg/sync/status.go

The api can return 403/402 for reasons the agent should just ignore, add some error types to make that feasible.

feat: Add expected error handling and some other tweaks

---

pkg/agent/agent.go
pkg/agent/publisher.go
pkg/manifests/cache.go
pkg/sync/loop.go
pkg/websocket/socket.go

This makes this code a bit more modular, and also should set us up well for listening for gate events.  Also covers preventing CRD deletion
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1206097337636687

feat: More robust wss publisher interface

---

pkg/agent/agent.go
pkg/manifests/template/common.go
pkg/manifests/template/helm.go
pkg/manifests/template/reader.go

cli-utils currently bails if a cluster scoped resource has a namespace field, which is not in-line with common helm behavior (many charts put namespaces in there even if they shouldn't).  This reimplements the reader and namespace setting logic to just set the namespace to empty string and log that it was wrong originally.

feat: Improve cli-utils manifest reader logic

---

.github/workflows/ci.yaml
pkg/manifests/template/common.go

The k8s api will eventually fail if they really don't exist so can rely on the statuses there.

feat: Don't fail on unknown gvks to avoid weird discovery client issues

---

pkg/sync/health.go
pkg/sync/status.go

The agent should intelligently understand CRD status. This generic method searches for `status` and fetches the conditions. If the condition `Ready` is true then the object is in a `healthy` state.
I have tested it with CD and Cluster API objects

feat: improve crd status

---

go.mod
go.sum
pkg/client/pipelines.go

This is both inefficient, and brittle to cases when the job is pruned on reruns.  Exposed the gate status in the api so we can do it properly (didn't realize it was never queryable).

fix: Don't sideload jobs in pipeline gate queries

---

pkg/manifests/template/raw.go

We were previously just referencing the go struct for a cluster, which bleeds out go's atypical casing for struct keys.  This will coerce things to something a bit more typical for end users in templates.

Fix cluster casing

---

internal/utils/kubernetes.go

Use the same fix as w/ the cli, need to be smarter about checking namespace existence to handle admission controllers firing first.

fix: Use better namespace upsert in agent too

---

pkg/controller/service/reconciler.go
pkg/manifests/template/cache.go
pkg/manifests/template/common.go
pkg/manifests/template/raw.go
pkg/manifests/template/reader.go

For some reason this only has popped up when trying to sync opa constraints but there are two major inefficiencies w/ manifest reader right now:
* has to go through RESTMapper to check namespacing (this can sometimes result in a network call, so caching is a meaningful optimization)
* Apparently it doubles the array on each cycle because it calls read on its own result list.  Think we've only used small sets of files for raw resources prior so never became an issue, but it's definitely an issue at large file sets (as you suddenly have a result of like 48k)

fix: Fix manifest reader inefficiency

---

go.mod
go.sum
internal/utils/kubernetes.go
internal/utils/maps.go
pkg/controller/namespaces/reconciler.go
pkg/controller/service/reconciler.go

The agent adds labels/annotations to namespaces from `Service.SyncConfig.NamespaceMetadata`

fix: respect Service.SyncConfig.NamespaceMetadata

---

pkg/manifests/template/raw.go
pkg/manifests/template/utils.go

Using the sprig library can create an unfortunate devex since pipe arguments work differently in text/template vs liquid.  This should solve for that.

feat: Invert arg order for many liquid filters

---

.github/workflows/publish-harness.yaml
charts/deployment-operator/templates/deployment.yaml
pkg/controller/stacks/job.go

The reconciler wasn't correctly specifying the harness image given surrounding information.  This should be a slightly better default.

fix: Fix image inference for stack runs

---

dockerfiles/harness/base.Dockerfile
internal/helpers/env.go
internal/helpers/file.go
pkg/harness/controller/controller.go
pkg/harness/environment/environment.go
pkg/harness/tool/terraform/modifier.go

With the new mountPath spec, you can assume users specify a full/correct path in harness

fix: Fix filepath setup

---

pkg/harness/stackrun/v1/types.go

Thinks we're using the wrong env var for access token

fix: Fix binding of plural creds

---

cmd/harness/args/args.go
cmd/harness/main.go
pkg/harness/controller/controller.go
pkg/harness/controller/controller_hooks.go
pkg/harness/controller/controller_options.go
pkg/harness/controller/controller_types.go
pkg/harness/exec/exec.go
pkg/harness/exec/exec_options.go
pkg/harness/exec/exec_types.go
pkg/harness/tool/ansible/ansible.go
pkg/harness/tool/terraform/terraform_types.go

- Use defer to ensure `postStart` hook is always executed in the controller. Previously, `postStart` was often being called twice, both by `Start` and `Finish` methods.
- Optimize approval check

feat(harness): add proper timeout handling for stack run step

---

go.mod
go.sum
pkg/harness/controller/controller.go
pkg/harness/controller/controller_hooks.go
pkg/harness/exec/analyzer.go
pkg/harness/exec/analyzer_heuristic.go
pkg/harness/exec/analyzer_types.go
pkg/harness/exec/exec.go
pkg/harness/exec/exec_options.go
pkg/harness/exec/exec_types.go

- Fix a bug with exec error handling. It was overriding `err` variable instead of shadowing it, often causing `err` to be overridden with `nil`.
Added a post-step run output analysis to detect potential errors in case the executable returned with exit code 0. It does a couple of things:
- Captures `stderr` and `stdout` outputs separately
- Runs after every step. It should be safe enough with specialized keyword detection and not trigger false positives.
- In case `stderr` output is not empty it will always consider the step as failed
- Runs a further analysis on `stdout` output with a keyword detection based on specialized messages. Currently, it is configured to look for the below strings:
- `error message: http remote state already locked`, ignore case: `true`
- `error acquiring the …

fix: add custom step output scanner with error detection

---

cmd/agent/agent.go
cmd/agent/options.go
internal/helpers/poll.go
pkg/controller/service/reconciler.go

- Use structured logging for top-level agent error logs
- Use non-deprecated polling function for `APIVersions` map updates
- Bump default number of concurrent reconciles to 20

fix: do not allow discovery api call for helm templating to stop the agent

---

Dockerfile

Needed to make api discovery caches actually work (wonder if this is also adding a lot of agent latency)

fix: chown /.kube dir

---

internal/kstatus/watcher/common.go
internal/kstatus/watcher/object_status_reporter.go
pkg/cache/resource_cache.go

It looks like OPA Gatekeeper uses irregular GroupVersionResource values (and this is a fringe possibility for other resources as well), that the inflect-based logic we were using fails for.  Just getting this from the RestMapper mimics cli-utils existing functionality and is more robust
Fixes PROD-2425

fix: Work on fix for status bug

---

charts/deployment-operator/Chart.yaml
internal/errors/base.go
pkg/harness/controller/controller.go
pkg/harness/stackrun/helpers.go
pkg/harness/tool/terraform/terraform.go

My local test code
```go
err := plural.Stacks.WithClient(client).Complete("0190bad3-f81c-4629-a1a9-ea7d683c7187", &console.StackRunAttributes{
Status: console.StackStatusSuccessful,
State: &console.StackStateAttributes{
Plan:  lo.ToPtr(generator.Strings.Random(30_000_000)),
State: generator.Stacks.State(20_000),
},
})
if err != nil {
log.Fatal(err)
}
```
Output
```bash
2024/07/19 14:44:59 got error, running modifier: {"networkErrors":{"code":413,"message":"Response body \"Request Entity Too Large\""},"graphqlErrors":null}
2024/07/19 14:44:59 dropping state
2024/07/19 14:45:01 got error, running modifier: {"networkErrors":{"code":413,"message":"Response body \"Request Entity Too Large\""},"graphqlErrors":null}
2024/07/19 14:45:01 dropping plan
Completed stack run
```

fix(harness): retry CompleteStackRun with less data on entity too large

---

internal/controller/status_controller.go

To get rid of the finalizer I used EventFilter which is called before `Reconcile` method. It prevents the situation when `r.Get(ctx, req.NamespacedName, configMap)` return `NotFound` error and we can't properly clean up the inventory cache.

feat: remove status controller finilizer

---

pkg/harness/tool/terraform/terraform.go

This should ensure that if terraform show command fails, it will also print any errors logged on the stderr.

fix(harness): improve exec with output logging

---

go.mod
go.sum
internal/helpers/env.go
pkg/harness/controller/controller.go
pkg/harness/stackrun/v1/types.go
pkg/harness/tool/ansible/ansible.go
pkg/harness/tool/ansible/ansible_types.go
pkg/harness/tool/ansible/modifier.go
pkg/harness/tool/ansible/modifier_types.go
pkg/harness/tool/terraform/terraform.go
pkg/harness/tool/terraform/terraform_types.go
pkg/harness/tool/tool.go

Tested with the following stack.
```terraform
resource "random_string" "random" {
length  = var.random_string_length
upper   = var.random_string_upper
special = var.random_string_special
}
resource "null_resource" "default" {
provisioner "local-exec" {
command = "${var.null_resource_command} ${random_string.random.result}"
}
}
output "test" {
value = random_string.random.result
}
```
```terraform
variable "random_string_length" {
type = number
default = 5
}
variable "random_string_upper" {
type = bool
default = false
}
variable "random_string_special" {
type = bool
default = false
}
variable "null_resource_command" {
type = string
default = "echo"
}
```
```yaml
apiVersion: deployments.plural.sh/v1alpha1
kind: InfrastructureStack
metadata:
name: floreks-stack-variables-basic
namespace: …
```

feat(harness): add stackrun variables support to terraform

---

pkg/harness/tool/terraform/terraform.go

Should write some tests against this but for now should fix

fix: Handle nil variables properly

---

internal/controller/stackrunjob_controller.go

Check if the job's Pod has started successfully. Otherwise, kill the job and set the `failed` status

feat: check pending job's Pod

---

internal/controller/upgradeinsights_cloudprovider.go

This should force aws client to fallback to using ec2 metadata service if running inside the aws.

fix(upgradeinsights): use ec2imds region resolver to create aws client

---

cmd/agent/kubernetes.go
cmd/agent/main.go
internal/controller/metricsaggregate.go

Replace controller runtime client with dedicated metrics client to avoid resource cache

fix: metricsaggregate sporadic errors

---

cmd/agent/args/args.go
go.mod
go.sum
pkg/common/health.go
pkg/common/health_test.go
pkg/common/suite_test.go
pkg/manifests/template/helm.go
pkg/manifests/template/helm_test.go
test/helm/yet-another-cloudwatch-exporter/templates/job.yaml

- add `IgnoreHooks` for helm templating
- set a healthy state as a default for CRD without a condition block
- add unit tests to cover new functionalities

feat: reconcile helm resources with hooks + set a healthy state as a default for CRD without a condition block

---

internal/kstatus/statusreaders/common.go
internal/kstatus/statusreaders/default.go
internal/kstatus/statusreaders/deployment.go
internal/kstatus/statusreaders/replicaset.go
internal/kstatus/statusreaders/statefulset.go
internal/kstatus/watcher/watcher.go

Get status directly from the Deployment, ReplicaSet and StatefulSet objects

feat: add custom status readers

---

internal/controller/vulnerabilityreports_controller.go

Keep the full set in memory and append it to that set, only remove it from that set when a reconcile fires with a deletionTimestamp set.

chore: improve Vulnerability Report Reconciler

---

internal/controller/kubecostextractor_controller.go

Need to remove all kube proxy usage, also bump timeouts and change window to explicit "monthly" param

fix: Rework kubecost extractor for in-cluster deployment

---

cmd/agent/args/args.go
cmd/agent/kubernetes.go
cmd/agent/main.go
go.mod
go.sum
internal/controller/kubecostextractor_controller.go

- add nodeCost and controlPlaneCost to cluster cost scrapes
- add jitter to kubecost extraction
- add `enable-kubecost-proxy` flag

feat: get node and control plane costs

---

charts/deployment-operator/Chart.yaml
charts/deployment-operator/values.yaml

Bump agentk to the latest version `0.0.2` with fixed CVE's

chore: bump agentk version in helm chart

---

api/v1alpha1/virtualcluster_types.go
go.mod
go.sum
internal/controller/upgradeinsights_cloudprovider.go
internal/controller/upgradeinsights_controller.go
pkg/client/console.go
pkg/client/upgradeinsights.go
pkg/harness/signals/context.go
pkg/test/mocks/Client_mock.go

It scrapes addons information from the EKS cluster and uses updated `saveUpgradeInsights` API to send it to Console.

feat: extend eks upgrade insights with addons information

---

internal/controller/kubecostextractor_controller.go
pkg/cache/resource_cache_entry.go

- fetch resource requests directly from the workload object
- wipe service status if a service is cached and an error occurs

fix: kubecost extractor

---

pkg/common/common.go
pkg/common/health.go
pkg/common/health_test.go

This can prevent the ui from overfailing resources/services

fix: Only apply stale-if-fail health checks to whitelisted gvks

---

pkg/harness/controller/controller_hooks.go

<p><a href="https://linear.app/pluralsh/issue/PROD-3218/harness-shouldnt-set-service-errors-when-stack-is-cancelled">PROD-3218</a></p>

fix(harness): do not send an error if stack run was cancelled

---

pkg/controller/service/reconciler.go
pkg/manifests/cache.go

We did not clear the cache when the service was deleted not from the UI.

fix: delete manifest cache on service delete

---

internal/controller/clusterdrain_controller.go
internal/utils/kubernetes.go
pkg/common/common.go
pkg/common/health.go
pkg/scraper/component_scraper.go

We don't have complete information about those three workloads. They can be in a pending state forever, and we don't know this. The only way is to additionally check the pods' statuses.

fix: fetch pods status for pending Deployment,DaemonSet and StatefulSet

---

cmd/agent/console.go
cmd/agent/main.go
internal/controller/clusterdrain_controller.go
pkg/applier/filters/cache_filter_test.go
pkg/cache/resource_cache.go
pkg/cache/resource_cache_entry.go
pkg/cache/resource_cache_test.go
pkg/common/health_test.go
pkg/common/status.go
pkg/common/suite_test.go
pkg/controller/service/reconciler.go
pkg/controller/service/reconciler_status.go
pkg/controller/service/reconciler_test.go
pkg/controller/service/status_collector.go
pkg/scraper/component_scraper.go

Add health timeout for all progressing resources. Previously it was only done for Ai Insight Component Scraper. Now it's global

fix: resource health status

---

charts/deployment-operator/templates/deployment.yaml
charts/deployment-operator/values.yaml

Also, slightly extended default timeout and added initial delay before first checks will be executed.

feat: add configurable liveness and readiness probes to chart

---

.github/workflows/ci.yaml
.github/workflows/publish.yaml

See: https://docs.docker.com/build/ci/github-actions/multi-platform/#distribute-build-across-multiple-runners
Results:

chore: Split builds between ARM and AMD64

---

.github/workflows/ci.yaml
cmd/agent/kubernetes.go
pkg/common/status.go
pkg/scraper/component_scraper.go

- disable go client cache for the agent
- use a map to store the progress time for the health status

perf: deployment improvements

---

internal/controller/kubecostextractor_controller.go

Add multi-aggregation capability to `getAllocation` to retrieve pod-level allocations across Deployments, StatefulSets, and DaemonSets. Use this enhancement to return recommendations

feat: return recommendations for each pod in the parent object

---

.github/CODEOWNERS
cmd/agent/args/args.go
cmd/agent/console.go
internal/helpers/fetch_types.go
pkg/client/console.go
pkg/client/service.go
pkg/controller/service/reconciler.go
pkg/controller/service/reconciler_status.go
pkg/controller/service/reconciler_test.go
pkg/manifests/cache.go
pkg/test/mocks/Client_mock.go

fix: Manifest cache jitter

---

pkg/controller/service/reconciler_scraper.go

this technically internally panics when it tries to stringify before logging

fix: Fix log message

---

cmd/agent/args/args.go
pkg/controller/controller.go
pkg/manifests/tarball.go

Extends this to three hours to reduce the need for unnecessary downloads further

feat: Extend manifest cache duration

---

go.mod
go.sum

- add support for `encoding.merge` in the Helm Lua script

chore: bump polly to v0.2.3

---

pkg/controller/service/reconciler_status.go

Skip checking child pods for the Job. The database cache contains only failed pods, and the Job may succeed after a retry.

fix: Improve update status for Job

---

pkg/cache/db/cache_test.go
pkg/cache/db/queries.go

It was done on failing pods table before but after merging it with components table where clause wasn't added. This fixes the bug and adds tests to cover the changes.

fix: Fix cluster health score query

---

pkg/cache/resource_cache.go
pkg/common/k8s.go
pkg/scraper/servergroups.go

This is probably too resource intensive for its own good, dropping them for now

fix: Drop aquasecurity groups

---

cmd/agent/kubernetes.go
cmd/agent/main.go
internal/controller/metricsaggregate.go
internal/controller/metricsaggregate_controller_test.go
pkg/cache/db/cache.go
pkg/cache/db/cache_test.go
pkg/cache/db/queries.go
pkg/common/k8s.go
pkg/ping/build.go
pkg/ping/pinger.go
pkg/scraper/metrics.go

- Refactored metrics collection logic:
Moved the logic for fetching metrics from the MetricsAggregateReconciler to the scraper package.
- Improved accessibility of metrics:
Metrics are now accessible to both the Pinger and MetricsAggregate controllers.
- Extended ping request payloads:
Added additional cluster-related fields to ping.

feat: add additional cluster fields to ping requests

---

internal/helpers/poll.go
pkg/controller/controller.go
pkg/controller/controller_manager.go
pkg/controller/restore/reconciler.go
pkg/controller/service/reconciler.go

This apparently is still broken, the lastReconcileTime wasn't being initialized to a valid value (time.Now) and so since the new pollers slow-start, it would fail consistently.  Apparently only service reconcilers utilize the lastReconcile time, so only affected them.
Also adds a lot of logging - mostly was needed to figure out the root cause.
Fixes: PROD-3922
e2e
Test environment: https://console.plrldemo.onplural.sh

fix: Work on dynamic poller fixes

---

pkg/client/cluster.go
pkg/ping/pinger.go
pkg/ping/runtime_service.go

- Added runtime service mapping for cilium-operator to use its' version as the main cilium addon version
- Added heuristic search for version based on pod spec image name for cilium since their chart does not use well-known kubernetes version label
- Slightly refactored logic to be easier to understand
Test environment: https://console.plrl-dev-aws.onplural.sh

fix: cilium compatibilities not discovered

---

pkg/controller/controller.go
pkg/controller/controller_manager.go
pkg/controller/controller_manager_options.go
pkg/controller/test/common.go
pkg/controller/test/controller_basic_test.go
pkg/controller/test/controller_dynamic_poller_test.go
pkg/controller/test/controller_recover_test.go
pkg/controller/test/controller_supervisor_test.go
pkg/websocket/socket.go

Fix the race condition
Add unit tests for the controller manager:
- check Poll and Reconcile callbacks
- test dynamic poller
- test recovery scenario
- test controller manager supervisor
This is a good base for other tests to cover additional edge cases.
Test environment: https://console.plrl-dev-aws.onplural.sh/

test: add unit tests for controller manager

---

go.mod
go.sum

Has a more performant way of sending document ids
e2e
Test environment: https://console.plrldemo.onplural.sh/cd/clusters/fa83f9fd-4dcd-4778-94d1-0bde35cae95d/services/36ed839e-8d93-429c-b1b2-69519af81bb2/components/4c826cfb-1389-432f-89aa-adb639384ea3/info

fix: Bump go client
